### ISSUE TITLE
Error when running coupled.py example

### ISSUE THREAD

**Issue by agoncalvescoel** [usnistgov/fipy#1011] opened 2024-02-15 08:07 UTC
When I try to run the coupled.py example, I have the following error

```
(MYFIPYENV) anacoelho@HYHNB053:~/fipy$ FIPY_VIEWER=matplotlib python examples/diffusion/coupled.py
QStandardPaths: wrong permissions on runtime directory /run/user/1000/, 0755 instead of 0700
/home/anacoelho/miniconda3/envs/MYFIPYENV/lib/python3.11/site-packages/fipy/viewers/matplotlibViewer/__init__.py:122: UserWarning: Matplotlib1DViewer efficiency is improved by setting the 'datamax' and 'datamin' keys
  return Matplotlib1DViewer(vars=vars, title=title, axes=axes, **kwlimits)
Uncaught exception:
Traceback (most recent call last):
  File "/home/anacoelho/fipy/examples/diffusion/coupled.py", line 125, in <module>
    exec(fipy.tests.doctestPlus._getScript())
  File "<string>", line 103, in <module>
  File "/home/anacoelho/miniconda3/envs/MYFIPYENV/lib/python3.11/site-packages/fipy/viewers/__init__.py", line 131, in Viewer
    raise ImportError("Failed to import a viewer: %s" % str(errors))
ImportError: Failed to import a viewer: ['matplotlib: can only concatenate str (not "int") to str']
```

**Comment by guyer** [comment] 2024-02-15 17:13
Thank you for reporting. This is a duplicate of #961. I'll prioritize pushing out a fix.

**Closed by guyer** 2024-02-15 17:13 UTC
Labels: duplicate
