### ISSUE TITLE
Parallel implementation of periodic grids

### ISSUE THREAD

**Issue by wd15** [usnistgov/fipy#409] opened 2014-09-19 21:36 UTC
This was requested on the mailing list

http://article.gmane.org/gmane.comp.python.fipy/3376

 _Imported from trac ticket [#666](http://www.ctcms.nist.gov/cgi-bin/redirectLegacyMatforge.py?url=http://matforge.org/fipy/ticket/666),  created by wd15 on 01-28-2014 at 16:26, last modified: 01-28-2014 at 16:26_

**Comment by tapetersen88** [comment] 2017-04-20 14:00
I started using FiPy a few weeks ago, and came across the same issue: The parallel version of the periodic boundary conditions only applies the periodicity along the left/right faces. I will attempt to modify the code in the abstractGridBulider class and create a new mesh builder. Any additional advice is much appreciated! Great experience using FiPy otherwise.

**Comment by tapetersen88** [comment] 2017-04-20 21:52
It seems this issue was resolved for the periodic1DGrid. I was able to implement the periodic boundary conditions for the 2D and 3D structures for parallelized code by following code written for the 1D mesh.

**Comment by guyer** [comment] 2017-05-12 14:04
@tapetersen88 A pull request would be most welcome!

**Comment by guyer** [comment] 2017-10-08 15:33
Duplicate of #518

**Closed by guyer** 2017-10-08 15:33 UTC
Labels: enhancement, meshes
