### ISSUE TITLE
Cannot dot `CellVariable`s

### ISSUE THREAD

**Issue by dsseara** [usnistgov/fipy#1069] opened 2024-08-15 22:46 UTC
Hello,

I was trying to measure the magnitude of the gradient of a scalar field $a(x)$, i.e. $|\nabla a|^2$, but ran into an issue when using the `.dot()` function. I was able to reproduce the error with the following example:

```python
>>> import fipy as fp
>>> mesh = fp.Grid1D(nx=10)
>>> a = fp.CellVariable(mesh=mesh)
>>> a.dot(a)
Uncaught exception:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/danny/miniconda3/envs/fipy/lib/python3.10/site-packages/fipy/variables/operatorVariable.py", line 307, in __repr__
    return self._getRepresentation()
  File "/Users/danny/miniconda3/envs/fipy/lib/python3.10/site-packages/fipy/variables/binaryOperatorVariable.py", line 66, in _getRepresentation
    return "(" + operatorClass._getRepresentation(self, style=style, argDict=argDict, id=id, freshen=freshen) + ")"
  File "/Users/danny/miniconda3/envs/fipy/lib/python3.10/site-packages/fipy/variables/operatorVariable.py", line 87, in _getRepresentation
    representation = self._py3kInstructions(op=self.op, style=style, argDict=argDict, id=id, freshen=freshen)
  File "/Users/danny/miniconda3/envs/fipy/lib/python3.10/site-packages/fipy/variables/operatorVariable.py", line 234, in _py3kInstructions
    stack.append(stack.pop() + "(" + ", ".join(args) + ")")
TypeError: sequence item 2: expected str instance, tuple found
```

This may be related to #961 or #962.

I am using fipy version 3.4.4.

Thank you for the wonderful package!

**Comment by guyer** [comment] 2024-10-01 18:50
Thank you for the report and my apologies for the delayed response. I was on leave and had some health issues; sorry this got missed.

This is, I think, caused by the fix to #961. I have [pushed a fix](https://github.com/usnistgov/fipy/pull/1074).

- FWIW, `a.dot(a)` doesn't really make sense, since `a` is scalar, but `a.grad.dot(a.grad)` and `a.faceGrad.dot(a.faceGrad)` raise the same error.
- `a.dot(a).value` works. It's an issue with the representation of the operation.
- FYI, we have an [`a.mag`](https://pages.nist.gov/fipy/en/latest/generated/fipy.variables.meshVariable.html#fipy.variables.meshVariable.MeshVariable.mag) property, but its representation exhibits the same bug.

> Thank you for the wonderful package!

You're welcome!

**Closed** 2024-10-04 19:00 UTC
Labels: bug, variables
