### ISSUE TITLE
Plot FaceVariable with matplotlib

### ISSUE THREAD

**Issue by ajcoelho** [usnistgov/fipy#621] opened 2019-03-04 20:39 UTC
Let's say that `j` is a `CellVariable` and `s=-j.faceGrad[0]` (in a 1D grid). Now, `s` is a FaceVariable, and if I try to define

`viewer = Viewer(vars=s)` 

I get the error from matplotlib

`'matplotlib: x and y must have same first dimension, but have shapes (100,) and (101,)'`,

which I think it's because `Viewer` only accepts `CellVariables`, and thus the Viewer assumes that the array of the x-axis is the CellCenters of the mesh. Is there any way to circumvent this, i.e., to indicate the Viewer that he should use the Faces and not the Centers?

**Comment by guyer** [comment] 2019-03-04 22:10
Closing as a duplicate of #133.
At this point, all you can do is something manual like
```python
>>> mesh = fp.Grid1D(nx=100)
>>> j = fp.CellVariable(mesh=mesh, value=fp.numerix.sin(mesh.x / 20))
>>> s = -j.faceGrad[0]
>>> X = mesh.faceCenters[0]
>>> plt.plot(X.value, s.value)
```

**Closed by guyer** 2019-03-04 22:10 UTC
Labels: viewers

**Comment by ajcoelho** [comment] 2019-03-06 12:22
And how could I do that at the same time with viewers? That is, I wanted something like this:

`    
   
    for(step) in range(steps):
        # (Re)set residual values
	    current_residual = 1.0e100

	    #update_values
	    y1.updateOld()
	    y2.updateOld()

	    while current_residual > desired_residual:

		    current_residual = coupledEqs.sweep( dt=dt )
		    #print current_residual


	    viewer1.plot()
	    viewer2.plot()
        plt.plot(X.vaue, s.value)
        plt.show()`

but this doesn't work.

**Comment by guyer** [comment] 2019-03-06 16:07
You would likely need to create a Matplotlib figure, create a set of axes in that figure, and then tell the axes to plot your data.

**Comment by ajcoelho** [comment] 2019-03-06 19:16
Got it. Thanks!

**Comment by awa5114** [comment] 2019-04-02 13:21
Do the viewers work in the current version of fipy?

**Comment by guyer** [comment] 2019-04-02 13:51
Yes, `Viewers` work. There's nothing to be "repaired". They don't support plotting `FaceVariables`, but that's a lack of a feature, not something to repair.
